name: dio_mini
description: dio_mini help you for write basic dio methods
version: 0.0.3
homepage: https://github.com/MuhammetFatihAktug/DioMini.git

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
